### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hdra** [hdra/Pelican-Cid#1]
- [x] Customizable footer
- [x] Syntax highlight
- [x] Inline code highlight
- [x] Periodical Archives
- [x] Links to Tags and Categories lists
- [x] code width on mobile
- [x] Remove post tags on posts lists on category page
